server:
  port: 8765

management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    appname: gtd-es-api-gateway
    preferIpAddress: true

spring:
  application:
    name: gtd-es-api-gateway
  cloud:
    discovery:
      enabled: true
      client:
        health-indicator:
          enabled: true
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
