server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: gtd-es-query-side
  kafka:
    bootstrapServers: localhost:9092
    consumer:
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: net.mguenther.gtd.kafka.serialization.ItemEventDeserializer
      autoOffsetReset: latest
      enableAutoCommit: false
      isolationLevel: read_committed
    listener:
      ackMode: MANUAL

gtd:
  topic: topic-getting-things-done
  groupId: getting-thigns-done-query

management:
  security:
    enabled: false

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
  instance:
    appname: gtd-es-query-side
    preferIpAddress: true
